version: '3.4'

services:
  php:
    build:
      context: ./build/docker/php
      args:
        # LOCAL_USER_ID comes from .env file
        WWW_DATA_UID: ${LOCAL_USER_ID}
    depends_on:
      - mongo
    ports:
      - "9000:9000"
    #user:
    volumes:
      - .:/var/www/html

  nginx:
    build:
      context: ./build/docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public:ro

  mongo:
    # In production, you may want to use a managed database service
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/var/lib/mongodb/data:rw
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8081:8081"

volumes:
  mongodb-data: ~
