# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:cli-buster

    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose build
      - run: docker-compose up -d
      - run: vendor/bin/codecept build
      - run: vendor/bin/codecept run
